use mavenmovies;

-- Q.1--
select count(rental_id) from rental;

-- Q.2 --
select * from film;
select avg(rental_duration) from film;

-- Q.3 --
select * from customer;
select UPPER(first_name), UPPER(last_name) from customer;

-- Q.4 --
select * from rental;
select Month(rental_date), rental_id from rental;

-- Q.5 --
select count(rental_id), customer_id from rental group by customer_id;

-- Q.6 -- Find the total revenue generated by each staff member --
select * from payment;
select staff_id, sum(amount) from payment group by staff_id;

-- Q.7 -- Display the title of the movie, customer s first name, and last name who rented it --
select * from inventory;
select * from film;
select * from customer;
select * from rental;

select title, first_name, last_name from film join inventory on film.film_id = inventory.film_id join rental on inventory.inventory_id = rental.inventory_id join customer on customer.customer_id = rental.customer_id;

-- Q.8 -- Retrieve the names of all actors who have appeared in the film "Gone with the Wind --

select * from actor;
select * from film;
select * from film_actor;

select actor.actor_id, actor.first_name, actor.last_name from actor 
join film_actor on 
actor.actor_id = film_actor.actor_id 
join film on 
film_actor.film_id = film.film_id
where film.title = 'Gone with the Wind';

-- Group by --

-- Q.1 -- Determine the total number of rentals for each category of movies --

select * from film_category;
select * from film;
select * from rental;
select * from inventory;

select category_id, count(category_id) from film_category 
join film on film.film_id = film_category.film_id
join inventory on inventory.film_id = film.film_id
join rental on inventory.inventory_id = rental.inventory_id
group by film_category.category_id;

-- Q.2 -- Find the average rental rate of movies in each language --

select * from language;
select * from film;
select distinct language_id from film;

select language.name, avg(film.rental_rate) from film
join language on language.language_id = film.language_id group by language.name;

-- Q.3 -- Retrieve the customer names along with the total amount they've spent on rentals --

select * from customer;
select * from payment;
select * from rental;
select * from inventory;

select customer.customer_id, customer.first_name, customer.last_name, sum(payment.amount) from customer
join payment on payment.customer_id = customer.customer_id
join rental on rental.rental_id = payment.rental_id
group by customer.customer_id,customer.first_name, customer.last_name;


-- Q.4 -- List the titles of movies rented by each customer in a particular city --

-- couldn't solve it --


-- Q.5 -- Display the top 5 rented movies along with the number of times they've been rented --

-- couldn't solve --

-- Q.6 -- Determine the customers who have rented movies from both stores (store ID 1 and store ID 2) --

-- couldn't solve --
